### ISSUE TITLE
flrtvc module questions

### ISSUE THREAD

**Issue by fghoraishi** [IBM/ansible-power-aix#112]
Hi
We ran the flrtvc module successfully but need help to understand the reports we are getting.
We are also not sure how to get the apar.csv file? do we download it and put on the controller?

Here is what we got: 

dkda3229:root[/usr/sys/inst.images/work]# ls -ltr
total 765656
-rw-r-----    1 root     system      1372160 Sep 05 2014  nas1_fix.tar
-rwx------    1 root     system        11719 Aug 27 2015  LICENSE.txt
-rw-r--r--    1 root     system        36296 Jan 18 2019  flrtvc.ksh
drwxrwxr-x    2 root     system          256 Jan 18 2019  __MACOSX
-rw-r-----    1 root     system    178432000 Mar 30 13:02 gencore_fix.tar
-rw-r-----    1 root     system     23326720 Mar 30 13:02 bind_fix18.tar
-rw-r-----    1 root     system     45434880 Apr 14 15:02 openssl_fix33.tar
-rw-r-----    1 root     system    142694400 Jun 15 21:04 trace_fix.tar
-rw-r--r--    1 root     system       548946 Jun 23 09:50 hiper_security.csv
drwxr-x---    7 root     system          256 Jun 23 09:59 tardir
-rw-r-----    1 root     system        15467 Jun 23 10:07 FLRTVC-latest.zip
-rw-r-----    1 root     system       115031 Jun 23 10:07 lslpp.txt
-rw-r-----    1 root     system         9837 Jun 23 10:07 emgr.tx
from Frank (External) to Everyone:    10:10  AM

our playbook was:

---
- name: Flrtvc
  hosts: dkda3229
  gather_facts: false
  tasks:
  - name: Download patches for security vulnerabilities
    ibm.power_aix.flrtvc:
      apar: all
      path: /usr/sys/inst.images
      download_only: yes
#      csv: /mnt/unix/aix/ansible/playbooks/apar.csv

**Comment by JLRebello** [comment]
The flrtvc script generates a report like so:
Messages: details on errors/warnings.
0.report: output of flrtvc script, report and details on flrtvc error if any. 
1.parse: List of URLs to download and details on parsing error if any.
2.discover: List of epkgs found in URLs.
3.download: List of downloaded epkgs.
4.1.reject: List of epkgs rejected. Can be because installed levels do not match ifix required levels or because a file is or will be locked by an other ifix installation (refer to messages or log file for more details)
4.2.check: List of epkgs matching the prerequisites and trying to install
5.install: List of epkgs actually installed on the system.

For more information on the report, please refer to flrtvc.py comments:
https://github.com/IBM/ansible-power-aix/blob/dev-collection/plugins/modules/flrtvc.py

The apar.csv file:
The csv option is optional and represents a path to the apar csv file containing the description of the sec and hyper fixes. This file is usually transferred from the Fix Central server. You can avoid this large transfer by specifying the path to an already transferred file if one exists, but you don’t have to use this option.

The FLRTVC script works by downloading the apar csv file from the FLRT website using CURL or WGET, whichever your machine has installed. Then, it uses the commands "emgr -lv3" for interim fixes and "lslpp -Lcq" for installed filesets, and compares to the vulnerabilities reported in the apar.csv file. FLRTVC will report any findings in a compact or full (verbose) format. You shouldn’t have to download it yourselves.

Does that help?

**Comment by JLRebello** [comment]
Please let me know if you have any follow up questions. If not, I will go ahead and close the issue. Thanks.

**Comment by fghoraishi** [comment]
Thanks, please close the issue.

tks
Faad
