### ISSUE TITLE
check_mode for most of the modules

### ISSUE THREAD

**Issue by psyntium** [IBM/ansible-power-aix#256]
**Is your feature request related to a problem? Please describe.**
Most of the modules are missing `check_mode`. For example, `ibm.power_aix.filesystem`. The community version of `community.general.aix_filesystem` has the `check_mode`. Why can't the official module has the `check_mode`?

**Describe the solution you'd like**
`check_mode` should be available for most of the modules.

**Describe alternatives you've considered**
if no `check_mode` available, perhaps something like `action=show` or `action=display` to view the current status.

**Comment by nitismis** [comment]
Hi Shreyansh !
Can you please do some research on this feature and comeback with a solution or explanation ?

**Comment by schamola** [comment]
Hi, Nitish !
Yes, I'll do some research and come up with something.

**Comment by nitismis** [comment]
Hi @psyntium,
We went through the community modules and looked into their support for check_mode.
It seems that they are running any command (making changes) only when check_mode is false. In case of check_mode = True, they are just skipping everything. Can you suggest some use cases for that feature to us ? and in addition, our other collections are also not providing support for check_mode, so if you can suggest use cases, we can have discussion with opur global team because it's a huge change. As of now we are not planning this feature, until we have more requests to do so.

Thanks and Regards,
Nitish K Mishra
