### ISSUE TITLE
nim-suma is showing unexpcted error - AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by NeetJoy** [IBM/ansible-power-aix#275]
Plz see the below error while running demo_nim_suma.yml

ansible-playbook -i inventory.ini demo_nim_suma.yml -e "nim_clients=fvtever86-lp7"
[WARNING]: running playbook inside collection ibm.power_aix

PLAY [NIM check on AIX playbook] ****************************************************************************************************************************

TASK [Check, download and create the NIM resource to install latest updates] ********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'group'
[WARNING]: Platform aix on host xxxxxxxxxxxxxxxxxxxxx is using the discovered Python interpreter at /usr/bin/python3, but future installation of
another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.13/reference_appendices/interpreter_discovery.html for more information.
fatal: [xxxxxxxxxxxxxxxxxxxxx]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "module_stderr": "Shared connection to xxxxxxxxxxxxxxxxxxxxx closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/.ansible/tmp/ansible-tmp-1678185923.1014304-1001291-15677205267776/AnsiballZ_nim_suma.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/.ansible/tmp/ansible-tmp-1678185923.1014304-1001291-15677205267776/AnsiballZ_nim_suma.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/.ansible/tmp/ansible-tmp-1678185923.1014304-1001291-15677205267776/AnsiballZ_nim_suma.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.nim_suma', init_globals=dict(_module_fqn='ansible_collections.ibm.power_aix.plugins.modules.nim_suma', _modlib_path=modlib_path),\r\n  File \"/usr/opt/python3/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/opt/python3/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/opt/python3/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_nim_suma_payload_v942yn9_/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1077, in <module>\r\n  File \"/tmp/ansible_nim_suma_payload_v942yn9_/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1066, in main\r\n  File \"/tmp/ansible_nim_suma_payload_v942yn9_/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 873, in suma_download\r\n  File \"/tmp/ansible_nim_suma_payload_v942yn9_/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 541, in compute_rq_name\r\nAttributeError: 'NoneType' object has no attribute 'group'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP **************************************************************************************************************************************************
xxxxxxxxxxxxxxxxxxx : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by nitismis** [comment]
However the error seems to be because of c_rsh connection failure but this error should be handled from the nim module.

some details here:
[root@xxxxxxxxx playbooks]# ansible-playbook -i inventory.ini demo_nim_suma.yml -e "nim_clients=p10den4n-inst54" -vvv
ansible-playbook [core 2.13.7]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.13 (default, Jun 14 2022, 18:03:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /root/.ansible/collections/ansible_collections/ibm/power_aix/playbooks/inventory.ini as it did not pass its verify_file() method
script declined parsing /root/.ansible/collections/ansible_collections/ibm/power_aix/playbooks/inventory.ini as it did not pass its verify_file() method
auto declined parsing /root/.ansible/collections/ansible_collections/ibm/power_aix/playbooks/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /root/.ansible/collections/ansible_collections/ibm/power_aix/playbooks/inventory.ini as it did not pass its verify_file() method
Parsed /root/.ansible/collections/ansible_collections/ibm/power_aix/playbooks/inventory.ini inventory source with ini plugin
[WARNING]: running playbook inside collection ibm.power_aix
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: demo_nim_suma.yml ***************************************************************************************************************************************************************
1 plays in demo_nim_suma.yml

PLAY [NIM check on AIX playbook] **********************************************************************************************************************************************************
META: ran handlers

TASK [Check, download and create the NIM resource to install latest updates] **************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/ibm/power_aix/playbooks/demo_nim_suma.yml:11
<p10den4n-inst53.isst.aus.stglabs.ibm.com> ESTABLISH SSH CONNECTION FOR USER: root
<p10den4n-inst53.isst.aus.stglabs.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/09b130b169"' xxxxxxxxxxxxxxxxxxxxxxxxxx '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<xxxxxxxx> (0, b'/\n', b'')
<xxxxxxxx> ESTABLISH SSH CONNECTION FOR USER: root
<xxxxxxxxxxxxxxx> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/09b130b169"' p10den4n-inst53.isst.aus.stglabs.ibm.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /.ansible/tmp `"&& mkdir "` echo /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392 `" && echo ansible-tmp-1678697623.192524-1130083-240743436961392="` echo /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392 `" ) && sleep 0'"'"''
<xxxxxxxxxxxx> (0, b'ansible-tmp-1678697623.192524-1130083-240743436961392=/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392\n', b'')
 Attempting python interpreter discovery
 ESTABLISH SSH CONNECTION FOR USER: root
SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/09b130b169"' p10den4n-inst53.isst.aus.stglabs.ibm.com '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'python3.10'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.9'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.8'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
(0, b'PLATFORM\nAIX\nFOUND\n/usr/bin/python2.7\n/usr/bin/python\n/usr/bin/python\nENDFOUND\n', b'')
 Python interpreter discovery fallback (unsupported platform for extended discovery: aix)
Using module file /root/.ansible/collections/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py
 PUT /root/.ansible/tmp/ansible-local-11300788ovh89rp/tmputnajgaz TO /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py
 SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/09b130b169"' 
 (0, b'sftp> put /root/.ansible/tmp/ansible-local-11300788ovh89rp/tmputnajgaz /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py\n', b'')
 SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/09b130b169"' p10den4n-inst53.isst.aus.stglabs.ibm.com '/bin/sh -c '"'"'chmod u+x /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/ /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py && sleep 0'"'"''
 SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/09b130b169"' -tt p10den4n-inst53.isst.aus.stglabs.ibm.com '/bin/sh -c '"'"'/usr/bin/python2.7 /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py && sleep 0'"'"''
<p10den4n-inst53.isst.aus.stglabs.ibm.com> (1, b'****run_oslevel_cmd from thread.timedout is initialized****\r\n*****Machine is not master, executing nim_exec from line 278*****\r\n*******INSIDE nim_exec********\r\nCommand going to run is:[\'/usr/lpp/bos.sysmgt/nim/methods/c_rsh\', \'p10den4n-inst54\', \'( LC_ALL=C /usr/bin/oslevel -s ); echo rc=$?\']\r\n***********rc in nim_exec is non-zero: FAILED*********\r\n****************************\r\n6\r\n\r\n0042-006 c_rsh: (exec_nimsh_cmd) exec_cmd A remote host refused an attempted connect operation. \r\n\r\nnconn: connect() failed, errno is 79\r\nxxxxxxxxx: A remote host refused an attempted connect operation.\r\n\r\n*******clients_oslevel st 840 is:\r\n{\'p10den4n-inst54\': \'timedout\'}\r\n*********Max OSLEVEL************* is:\r\ntimedout\r\n*********Client Target OSLEVEL************* is:\r\n{\'p10den4n-inst54\': \'timedout\'}\r\nTraceback (most recent call last):\r\n  File "/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py", line 107, in <module>\r\n    _ansiballz_main()\r\n  File "/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py", line 48, in invoke_module\r\n    run_name=\'__main__\', alter_sys=True)\r\n  File "/opt/freeware/lib/python2.7/runpy.py", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File "/opt/freeware/lib/python2.7/runpy.py", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File "/opt/freeware/lib/python2.7/runpy.py", line 72, in _run_code\r\n    exec code in run_globals\r\n  File "/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 1093, in <module>\r\n  File "/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 1082, in main\r\n  File "/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 889, in suma_download\r\n  File "/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 557, in compute_rq_name\r\nAttributeError: \'NoneType\' object has no attribute \'group\'\r\n', b'Shared connection to p10den4n-inst53.isst.aus.stglabs.ibm.com closed.\r\n')
<p10den4n-inst53.isst.aus.stglabs.ibm.com> Failed to connect to the host via ssh: Shared connection to xxxxxxxx closed.
[WARNING]: Module invocation had junk after the JSON data: Traceback (most recent call last):   File "/.ansible/tmp/ansible-
tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py", line 107, in <module>     _ansiballz_main()   File "/.ansible/tmp/ansible-
tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py", line 99, in _ansiballz_main     invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)   File
"/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py", line 48, in invoke_module     run_name='__main__', alter_sys=True)   File
"/opt/freeware/lib/python2.7/runpy.py", line 176, in run_module     fname, loader, pkg_name)   File "/opt/freeware/lib/python2.7/runpy.py", line 82, in _run_module_code     mod_name,
mod_fname, mod_loader, pkg_name)   File "/opt/freeware/lib/python2.7/runpy.py", line 72, in _run_code     exec code in run_globals   File
"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 1093, in <module>   File
"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 1082, in main   File
"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 889, in suma_download   File
"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py", line 557, in compute_rq_name AttributeError: 'NoneType'
object has no attribute 'group'
x ESTABLISH SSH CONNECTION FOR USER: root
x SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/09b130b169"' p10den4n-inst53.isst.aus.stglabs.ibm.com '/bin/sh -c '"'"'rm -f -r /.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/ > /dev/null 2>&1 && sleep 0'"'"''
x(0, b'', b'')
[WARNING]: Platform aix on host p10den4n-inst53.isst.aus.stglabs.ibm.com is using the discovered Python interpreter at /usr/bin/python2.7, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.13/reference_appendices/interpreter_discovery.html for more information.
fatal: [xxxxxxxxxxxxxxxxxx]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python2.7"
    },
    "changed": false,
    "module_stderr": "Shared connection to xxxxxxxxxxxxxx closed.\r\n",
    "module_stdout": "****run_oslevel_cmd from thread.timedout is initialized****\r\n*****Machine is not master, executing nim_exec from line 278*****\r\n*******INSIDE nim_exec********\r\nCommand going to run is:['/usr/lpp/bos.sysmgt/nim/methods/c_rsh', 'p10den4n-inst54', '( LC_ALL=C /usr/bin/oslevel -s ); echo rc=$?']\r\n***********rc in nim_exec is non-zero: FAILED*********\r\n****************************\r\n6\r\n\r\n0042-006 c_rsh: (exec_nimsh_cmd) exec_cmd A remote host refused an attempted connect operation. \r\n\r\nnconn: connect() failed, errno is 79\r\np10den4n-inst54.isst.aus.stglabs.ibm.com: A remote host refused an attempted connect operation.\r\n\r\n*******clients_oslevel st 840 is:\r\n{'p10den4n-inst54': 'timedout'}\r\n*********Max OSLEVEL************* is:\r\ntimedout\r\n*********Client Target OSLEVEL************* is:\r\n{'p10den4n-inst54': 'timedout'}\r\nTraceback (most recent call last):\r\n  File \"/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/.ansible/tmp/ansible-tmp-1678697623.192524-1130083-240743436961392/AnsiballZ_nim_suma.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1093, in <module>\r\n  File \"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 1082, in main\r\n  File \"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 889, in suma_download\r\n  File \"/tmp/ansible_nim_suma_payload_Qr2vGQ/ansible_nim_suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/nim_suma.py\", line 557, in compute_rq_name\r\nAttributeError: 'NoneType' object has no attribute 'group'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ********************************************************************************************************************************************************************************
xxxxxxxxxxxxx: ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by nitismis** [comment]
still working on it.

**Comment by nitismis** [comment]
A defect for this issue has been opened in AIX. This is not really an issue of ansible and power_aix collection.
