### ISSUE TITLE
lvm_facts - Data collection of "pv" doesn't include None disks and old_rootvg

### ISSUE THREAD

**Issue by neikei** [IBM/ansible-power-aix#279]
**Describe the bug**
lvm_facts seems to be incomplete in the pv area, because None disks and disks of old_rootvg are missing. The error during the collection shows "Command 'lspv -L hdisk17' failed." 

**To Reproduce**

```bash
# Run the following task, when your system shows None/old_rootvg disks in the output of "lspv"

    - name: Update PV facts to existing LVM facts
      ibm.power_aix.lvm_facts:
        name: all
        component: pv
```

**Expected behavior**
All pvs should be visible in the data collection of lvm_facts.

**Environment (please complete the following information):**
OS: 7200-05-03-2148
Python Version: 2.7.18
Ansible Version: 2.9.25
AIX Collection Version: 1.5.1

**Comment by schamola** [comment]
Hi @neikei,
We looked into the issue, From LVM point of view, lspv command can only be used to display information about a physical volume within a volume group. So, It can't be used to get data about None disks.
In case of old_rootvg, It's not working because the vg needs to be varied on (using the varyonvg command), then it should work fine.

**Comment by neikei** [comment]
My expectation of the module was that it would show all pvs in "lspv", because "component: pv" implied that.

**Comment by neikei** [comment]
@schamola, please re-open the issue. A list of None disks is for example needed if you want to select them for vg operations like adding them to a vg.
