### ISSUE TITLE
Playbooks need to be re-worked (logic)

### ISSUE THREAD

**Issue by neikei** [IBM/ansible-power-aix#346]
It's an excellent idea to include playbooks for an easy start. However, these should also follow best practices and provide good examples.

In this example names do not match the tasks and tasks are executed without pre-check if the filesystem grow is really needed, so this will be executed every time and is not really idempotent.

https://github.com/IBM/ansible-power-aix/blob/240314e2d5ee9169219c0f99d53f70eb3b46c86b/playbooks/demo_apache-server.yml#L36-L46

**Comment by nitismis** [comment]
Hi @neikei 
In Q4 we are planning to work on playbooks and documentation. All the fixes and enhancements over a period of 2-3 years had led to the documentations also being a bit outdated. But rest assured that it is in our plan for Q4.

Thanks

**Comment by nitismis** [comment]
We have updated our documentations and most of the playbooks. This particular playbook is of no use as per current features provided by AIX toolbox or ansible collection because we have completely moved to dnf and yum is no more supported on AIX platform. If you find any issue in existing demo playbooks please do let us know. Thanks for the help !
