### ISSUE TITLE
Not able to reboot the AIX server with ansible automation platform

### ISSUE THREAD

**Issue by mpanwar2024** [IBM/ansible-power-aix#410]
We are not able to reboot the AIX LPAR with ansible automation platform, server has been rebooted but job never exited and continuously running. Please check and let us know if are missing anything.

Here is my ansible playbook.

---
- name: "Reboot the machine"
  hosts: all
  gather_facts: no
  vars:
    log_file: "/tmp/ansible_reboot_debug.log"
    pre_reboot_delay_v: 0
    post_reboot_delay_v: 0
    reboot_timeout_v: 0
    test_command_v: ""
  collections:
    - ibm.power_aix
  tasks:

    - name: "reboot the machine"
      reboot:
              pre_reboot_delay: "{{ pre_reboot_delay_v }}"
              post_reboot_delay: "{{ post_reboot_delay_v }}"
              reboot_timeout: "{{ reboot_timeout_v }}"
              test_command: "{{ test_command_v }}"
      register: reboot_result

    - debug: var=reboot_result

 - OS: [e.g. AIX 7.2]
 - Python Version: [3.6]
 - OpenSSH Version: [3.0.10]

ansible [core 2.15.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

**Comment by schamola** [comment]
Hi @mpanwar2024,
Thanks for reporting this issue, we are currently looking into it !

**Comment by nitismis** [comment]
There is some issue with openSSH on AIX. It is not keeping track of old connection, so, after reboot, controller node is not able to resume the connection. Which results in controller node waiting for connection infinitely and fails after timeout because it is not able to run the test command.
We are providing a work around in demo_reboot_workaround.yml because we dont know how much time it will take to resolve openSSH in AIX itself.
Thanks
