### ISSUE TITLE
Ansible Galaxy newer version?

### ISSUE THREAD

**Issue by ALutz273** [IBM/ansible-power-aix#525]
**Describe the bug**
why is there version 1.8.3 on ansible galaxy and only version 1.8.1 on github? 

What has been changed in the versions and why is it not published here?

**Comment by stephenulmer** [comment]
Furthermore, why aren’t there tags for versions after 1.7 in the repo? Are they there and I’m just not looking correctly?

**Comment by nitismis** [comment]
@ALutz273 1.8.2 and 1.8.3 were rejected by automation hub because of linting issues. They have recently updated their lint tools. This is the reason why we didn't run our github-actions for these version's release. Soon we will be uploading 1.8.4 and everything will be fine.
@stephenulmer .. 1.8.1 is tagged but it is not showing at the top, because of recent changes in our workflow. We have fixed it and everything will be fine by next week, once we release version 1.8.4.
Anyways, thanks for pointing out.
Closing this issue.

Thanks
